resources:
# Firewall rules
- name: latencia-firewall-django
  type: compute.v1.firewall
  properties:
    network: global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 0.0.0.0/0
    targetTags:
    - rest-django
    allowed:
    - IPProtocol: TCP
      ports:
      - 8080

- name: latencia-firewall-db
  type: compute.v1.firewall
  properties:
    network: global/networks/default
    priority: 1000
    direction: INGRESS
    sourceRanges:
    - 0.0.0.0/0
    targetTags:
    - database
    allowed:
    - IPProtocol: TCP
      ports:
      - 5432

# Redis instance
- type: compute.v1.instance
  name: vm-redis-cache
  properties:
    zone: us-west1-a
    machineType: zones/us-west1-a/machineTypes/custom-4-6144
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - redis-cache
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y redis-server
          sudo sed -i 's/^bind .*/bind 0.0.0.0/' /etc/redis/redis.conf
          sudo sed -i 's/^protected-mode yes/protected-mode no/' /etc/redis/redis.conf
          sudo systemctl restart redis-server

# DB Primary
- type: compute.v1.instance
  name: vm-db-primary
  properties:
    zone: us-west1-a
    machineType: zones/us-west1-a/machineTypes/custom-4-6144
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - database
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo -u postgres bash -c "echo \"listen_addresses = '*'\" >> /etc/postgresql/12/main/postgresql.conf"
          sudo -u postgres bash -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/12/main/pg_hba.conf"
          sudo systemctl restart postgresql
          sudo -u postgres psql -c "CREATE DATABASE clinico;"
          sudo -u postgres psql -c "CREATE USER django WITH PASSWORD 'password123';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE clinico TO django;"

# DB Replica
- type: compute.v1.instance
  name: vm-db-replica
  properties:
    zone: us-west1-a
    machineType: zones/us-west1-a/machineTypes/custom-4-6144
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - database
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y postgresql postgresql-contrib
          sudo -u postgres bash -c "echo \"listen_addresses = '*'\" >> /etc/postgresql/12/main/postgresql.conf"
          sudo -u postgres bash -c "echo \"host all all 0.0.0.0/0 md5\" >> /etc/postgresql/12/main/pg_hba.conf"
          sudo systemctl restart postgresql
          sudo -u postgres psql -c "CREATE DATABASE clinico;"
          sudo -u postgres psql -c "CREATE USER django WITH PASSWORD 'password123';"
          sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE clinico TO django;"

# Django instance template
- name: django-instance
  type: compute.v1.instance
  properties: &django-instance
    zone: us-west1-a
    machineType: zones/us-west1-a/machineTypes/custom-4-6144
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        sourceImage: projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts
    networkInterfaces:
    - network: global/networks/default
      accessConfigs:
      - name: External NAT
        type: ONE_TO_ONE_NAT
    tags:
      items:
      - rest-django
    metadata:
      items:
      - key: startup-script
        value: |
          #!/bin/bash
          sudo apt-get update
          sudo apt-get install -y python3-pip git python3-dev libpq-dev

          sudo mkdir -p /app
          cd /app
          git clone https://github.com/danteboe/ExpLatenciaSprint4.git .

          DB_PRIMARY_IP=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/db-primary-ip)
          DB_REPLICA_IP=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/db-replica-ip)
          REDIS_IP=$(curl -H "Metadata-Flavor: Google" http://metadata.google.internal/computeMetadata/v1/instance/attributes/redis-ip)

          # Crear db_config.py
          cat > db_config.py << EOF
          DATABASES = {
              'default': {
                  'ENGINE': 'django.db.backends.postgresql',
                  'NAME': 'clinico',
                  'USER': 'django',
                  'PASSWORD': 'password123',
                  'HOST': '${DB_PRIMARY_IP}',
                  'PORT': '5432',
              },
              'replica': {
                  'ENGINE': 'django.db.backends.postgresql',
                  'NAME': 'clinico',
                  'USER': 'django',
                  'PASSWORD': 'password123',
                  'HOST': '${DB_REPLICA_IP}',
                  'PORT': '5432',
              },
          }
          DATABASE_ROUTERS = ['latencia.dbrouter.PrimaryReplicaRouter']
          EOF

          mkdir -p latencia
          cat > latencia/dbrouter.py << 'EOF'
          class PrimaryReplicaRouter:
              """
              Database router that sends reads to replica and writes to primary DB
              """
              def db_for_read(self, model, **hints):
                  return 'replica'
              def db_for_write(self, model, **hints):
                  return 'default'
              def allow_relation(self, obj1, obj2, **hints):
                  return True
              def allow_migrate(self, db, app_label, model_name=None, **hints):
                  return True
          EOF

          sed -i "s|redis://redis:6379/1|redis://${REDIS_IP}:6379/1|g" settings.py

          # Script Python para reemplazar bloque DATABASES
          cat > replace_databases.py << 'PYEOF'
          import re
          with open('settings.py') as f:
              content = f.read()
          with open('db_config.py') as f:
              db_conf = f.read()
          pattern = re.compile(r'DATABASES\s*=\s*\{.*?\}\s*', re.DOTALL)
          content_new = pattern.sub(db_conf + '\n', content)
          with open('settings.py', 'w') as f:
              f.write(content_new)
          PYEOF

          python3 replace_databases.py
          rm replace_databases.py

          # Insertar import si no existe
          grep -q "from .views import generar_reporte_clinico" urls.py || sed -i '1i from .views import generar_reporte_clinico' urls.py

          sed -i "s/^ALLOWED_HOSTS = .*/ALLOWED_HOSTS = ['*']/" settings.py

          pip3 install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py runserver 0.0.0.0:8080

# VM reporte clinico 1
- type: compute.v1.instance
  name: vm-reporte-clinico-1
  properties:
    <<: *django-instance
    metadata:
      items:
      - key: db-primary-ip
        value: $(ref.vm-db-primary.networkInterfaces[0].networkIP)
      - key: db-replica-ip
        value: $(ref.vm-db-replica.networkInterfaces[0].networkIP)
      - key: redis-ip
        value: $(ref.vm-redis-cache.networkInterfaces[0].networkIP)

# VM reporte clinico 2
- type: compute.v1.instance
  name: vm-reporte-clinico-2
  properties:
    <<: *django-instance
    metadata:
      items:
      - key: db-primary-ip
        value: $(ref.vm-db-primary.networkInterfaces[0].networkIP)
      - key: db-replica-ip
        value: $(ref.vm-db-replica.networkInterfaces[0].networkIP)
      - key: redis-ip
        value: $(ref.vm-redis-cache.networkInterfaces[0].networkIP)
